Rails: Task 2
SleepyDany/RoR_lessons_2 pull request #1
Opened 2021-06-18 20:45 UTC by SleepyDany

Изучение Rails от Thinknetica.
Задание 2.

2021-06-19 14:41 UTC, VidgarVii requested changes

2021-06-19 14:41 UTC, VidgarVii commented on README.md
> +  База данных
список сущностей приложения обычно выводится из сценария использования приложения

сценарий использования приложения примерно такой:
- Пользователь заходит на сайт
- он выбирает Тест
- Тест может принадлежать к одной из Категорий
- Тест состоит из Вопросов
- на каждый Вопрос есть несколько Ответов
- Пользователь выбирает один или несколько Ответов, чтобы ответить на каждый из Вопросов
- Результат тестирования сохраняется

2021-06-19 14:41 UTC, VidgarVii commented on config/initializers/initializer.rb
> +Rails.application.config.version = '0.1.0'
по ТЗ нужно "добавить инишиалайзер", т.е. директория должна быть `initializers`
в ней нужно создать новый файл (логично будет назвать его `version.rb`)
там нужно инициализировать константу (и не забудь, что она должна быть объявлена не "в воздухе", а в "контексте приложения", т.е. как минимум внутри модуля `TestGuru`

2021-06-19 14:41 UTC, VidgarVii commented on config/locales/ru.yml
> +  hello: "Hello world"
отлично, что не забыл добавить файл. Только комменты тут лишние

2021-06-19 14:41 UTC, VidgarVii commented on public/about.html
> +</html>
супер!

2021-06-21 05:41 UTC, VidgarVii requested changes

2021-06-21 05:41 UTC, VidgarVii commented on README.md
> +  Меню
меню это не сущность. А элемент ui. с веб компонентами и выделять их как сущности точно не будем

2021-06-21 05:41 UTC, VidgarVii commented on README.md
> +  База данных
БД тоже не стоит выделать как сущность

2021-06-21 05:41 UTC, VidgarVii commented on config/application.rb
> +    VERSION
так точно не стоит делать. Зачем нам объявленная пустая константа? тем более когда уже есть config/initializers/version.rb
Вот там и должна быть вся реализация.
Итог должен быть такой, что через консоль можно было получить текущую версию ПО через Test::Guru::Application::VERSION

2021-06-21 13:22 UTC, VidgarVii requested changes

2021-06-21 13:22 UTC, VidgarVii commented on config/initializers/version.rb
> +TestGuru::Application::VERSION = '0.1.2'
где тут модуль где тут класс?
Что за синтаксис такой?
когда пишешь код развернуто
module TestGuru
  class Application
    ...

2021-06-21 13:22 UTC, VidgarVii commented on config/initializers/version.rb
> +TestGuru::Application::VERSION = '0.1.2'
сразу про константы следующий момент:

"мутабельные" объекты (строки, хэши, массивы) рекомендуется `freeze`-ить, чтобы они были неизменяемыми
в противном случае константу, ссылающуюся на "мутабельный" объект,  можно изменить: `VERSION << '3.14..'`

2021-06-21 13:27 UTC, SleepyDany commented on config/initializers/version.rb
> +TestGuru::Application::VERSION = '0.1.2'
> где тут модуль где тут класс?
> Что за синтаксис такой?
> когда пишешь код развернуто
> module TestGuru
> class Application
> ...

Вот с этим и вопрос, в файле application.rb такие модуль и класс уже заданы, разве это не будет переопределением уже созданных?

2021-06-25 16:57 UTC, merged