Rails: Task4 - Active Record Query Interface
SleepyDany/RoR_lessons_2 pull request #3
Opened 2021-07-01 00:18 UTC by SleepyDany

Изучение Rails от Thinknetica.
Задание 4: интерфейс запросов ActiveRecord.

2021-07-01 09:27 UTC, VidgarVii requested changes

2021-07-01 09:27 UTC, VidgarVii commented on db/migrate/20210626174414_create_tests.rb
> +    add_reference :users, :passed_tests, foreign_key: {to_table: :tests}
Промахнулся. ключ создаётся юзерам, а миграция создания таблицы тестов...

2021-07-01 09:27 UTC, VidgarVii commented on app/models/test.rb
> +    Test.joins("INNER JOIN categories ON tests.category_id = categories.id").where("categories.title
писать Test нет смысла, так как согласно парадигме ООП при вызове методов всегда идёт обращение к какому-то объекту. В данному случаи, так как это метод класса, это объект Test
Т.е. можно сразу начинать писать

***

```ruby
def self.by_category(category)
  joins('JOIN categories ON tests.category_id = categories.id')

2021-07-01 09:27 UTC, VidgarVii commented on app/models/test.rb
> +    Test.joins("INNER JOIN categories ON tests.category_id = categories.id").where("categories.title
INNER используется по умолчания. тоже можно не писать

2021-07-01 09:27 UTC, VidgarVii commented on app/models/test.rb
> +    Test.joins("INNER JOIN categories ON tests.category_id = categories.id").where("categories.title
в where order pluck лучше использовать хеши или сиволы. Так безопасней

order(title: :desc)

2021-07-01 09:27 UTC, VidgarVii commented on app/models/user.rb
> +    Test.where('level = ?', level).find(self.passed_tests_id)
задачку про "пройденные тесты" правильно решать через соединительную таблицу
нужно добавить модель, к примеру `Result` или `TestsUser` и соответсвенную таблицу (`tests_users` или `results`)... или `TestPassage` и `test_passages`
в общем нужны "промежуточная модель" и "соединительная таблица"
такая таблица ("соединительная") обычно в минимальном виде хранит два внешних ключа на таблицы, которые соединяет
когда пользователь проходит тест в этой таблице должна появляться запись содержащая соответсвенно ай-ди этого пользователя и ай-ди пройденного теста
(подробней можешь посмотреть в документации к рельсам про соединительные модели, таблицы)

в простейшем варианте, который в общем-то очень часто используется, в соединительной таблице всего два поля (кроме ай-ди)
в нашем случае это будут `user_id`, `test_id` - если в таблице существует запись для пары тест-юзер, то юзер этот тест проходил (при прохождении теста нужно будет создать такую запись), если записи нет, то тест не пройден
с помощью этого механизма можно хранить информацию о прохождении любого количества тестов любым количеством пользователей

2021-07-01 09:28 UTC, VidgarVii requested changes

2021-07-01 09:28 UTC, VidgarVii commented on db/seeds.rb
> +tests = Test.create([{ title: 'Введение в Ruby', category_id: categories.first.id, author_id: 1 },
лучше использовать `create!` - метод бросит исключение, если запись не создастся
сразу будет видно, если что-то пошло не так

2021-07-01 09:28 UTC, VidgarVii commented on db/seeds.rb
> +questions = Question.create([{ text: '5 + 5 = ?', test_id: 2 },
"хардкодить" `id` - не очень хорошая затея
такой "сид" невозможно накатить на существующую базу, ведь там id могут быть заняты другими записями или вовсе отсутствовать
правильней воспользоваться тем, что метод `create` возвращает созданные записи

2021-07-02 06:59 UTC, VidgarVii requested changes

2021-07-02 06:59 UTC, VidgarVii commented on app/models/test.rb
> +   joins('JOIN categories ON tests.category_id = categories.id').where("categories.title
where тоже перевидит на хеш. Пусть AR строит за тебя запросы

2021-07-02 06:59 UTC, VidgarVii commented on app/models/user.rb
> +        .where("tests.level = :level AND results.user_id = :id", level: level, id: id)
тоже самое. используй хеши

2021-07-02 06:59 UTC, VidgarVii commented on db/seeds.rb
> +answers = Answer.create!([{ text: '10', correct: true, question_id: questions[0].id },
переменная answers не используется. Сейчас она просто забивает оперативную память и мешает работе GC
тоже самое про results

2021-07-02 09:53 UTC, SleepyDany commented on db/seeds.rb
> +answers = Answer.create!([{ text: '10', correct: true, question_id: questions[0].id },
> переменная answers не используется. Сейчас она просто забивает оперативную память и мешает работе GC
> тоже самое про results

После заполнения results он в join-е используется, может вы имели в виду вопросы и ответы?

2021-07-02 14:31 UTC, VidgarVii requested changes

2021-07-02 14:31 UTC, VidgarVii commented on app/models/test.rb
> +   #        = ?", category).order(title: :desc).pluck(:title)
мусорные коммента надо удалять

2021-07-02 14:31 UTC, VidgarVii commented on app/models/test.rb
> +  end
```
joins('JOIN categories ON tests.category_id = categories.id')
  .where(categories: { title: category })
  .order(title: :desc)
  .pluck(:title)
```

2021-07-02 14:31 UTC, VidgarVii commented on db/seeds.rb
> +                         { user_id: users.last.id, test_id: tests.last.id }])
1 нет ответов.
2 переменая results не используется. лучше такие не создавать
3 Данных мало

2021-07-03 15:14 UTC, merged